version: '2'

services:
    elasticsearch:
        build: elasticsearch/
        container_name: bf_elasticsearch
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - bf_elasticsearch:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - commom

    kibana:
        build:  kibana/
        container_name: bf_kibana
        volumes:
            - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        networks:
            - commom

    mysql:
        build: mysql/
        container_name: bf_mysql
        volumes:
            - bf_mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        env_file:
            - ./mysql/.env
volumes:
    bf_elasticsearch:
        driver: local
    bf_mysql:
        driver: local

networks:
    commom:
        driver: bridge